# Generated by Django 4.2.25 on 2025-10-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_direccion', models.CharField(max_length=255)),
                ('total_orden', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Preparación'), ('PREPARANDO', 'En Preparación'), ('ENVIADO', 'En Camino'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_url', models.CharField(max_length=200)),
                ('es_promocion', models.BooleanField(default=False)),
                ('es_especialidad', models.BooleanField(default=False)),
                ('tipo_producto', models.CharField(choices=[('entero', 'Pollo Entero'), ('presas', 'Pollo por Presas'), ('combo', 'Combo de Pollo'), ('otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.producto')),
            ],
        ),
    ]
